package vertiplat;

public class GUI extends javax.swing.JPanel {

    private final BaseLevel     world;

    public GUI(BaseLevel world) {
        initComponents();
        this.world = world;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pausedToggle = new javax.swing.JToggleButton();
        restartButton = new javax.swing.JButton();

        pausedToggle.setText("Paused");
        pausedToggle.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pausedToggleStateChanged(evt);
            }
        });
        pausedToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pausedToggleActionPerformed(evt);
            }
        });

        restartButton.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        restartButton.setText("Restart");
        restartButton.setMaximumSize(new java.awt.Dimension(69, 15));
        restartButton.setMinimumSize(new java.awt.Dimension(69, 15));
        restartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pausedToggle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 276, Short.MAX_VALUE)
                .addComponent(restartButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pausedToggle))
            .addComponent(restartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pausedToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pausedToggleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pausedToggleActionPerformed

    private void pausedToggleStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pausedToggleStateChanged
        world.setPaused(true);
    }//GEN-LAST:event_pausedToggleStateChanged

    private void restartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartButtonActionPerformed
        // TODO add your handling code here:
        //world.startLevel();
    }//GEN-LAST:event_restartButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton pausedToggle;
    private javax.swing.JButton restartButton;
    // End of variables declaration//GEN-END:variables
}
